All:tcp_cli tcp_srv_thread
#All:tcp_cli tcp_srv_process
tcp_cli:tcp_cli.cpp
		g++ $^ -o $@
tcp_srv_process:tcp_srv_process.cpp
		g++ $^ -o $@
tcp_srv_thread:tcp_srv_thread.cpp
		g++ $^ -o $@ -lpthread


