sigprocmask:sigprocmask.c
	gcc $^ -o $@
sigaction:sigaction.c
	gcc $^ -o $@
signal:signal.c
	gcc $^ -o $@
sigprocmask:sigprocmask.c
	gcc $^ -o $@
zombie:zombie.c
	gcc $^ -o $@
test:test.c
	gcc $^ -o $@

